services:
  n8n:
    image: n8nio/n8n:2.21.7
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_SECURE_COOKIE=false
      - N8N_COMMUNITY_PACKAGES_ENABLED=true
      - GENERIC_TIMEZONE=Asia/Shanghai
      - TZ=Asia/Shanghai
      - N8N_ALLOWED_FILE_ACCESS=/home/node/.n8n-files
      - N8N_RUNNERS_TASK_TIMEOUT=3600
      - NODES_EXCLUDE=[]
    volumes:
      - /Users/a2333/.n8n:/home/node/.n8n
      - /Users/a2333/.n8n-files:/home/node/.n8n-files
      - /Users/a2333/IDE/n8n/articles:/home/node/.n8n-files/articles
      - /Users/a2333/IDE/n8n/lmg:/home/node/.n8n-files/lmg
      - /Users/a2333/IDE/n8n/horizon/data/summaries:/home/node/.n8n-files/horizon-summaries
      - /Users/a2333/IDE/n8n/horizon/data/summaries/archive:/home/node/.n8n-files/horizon-archive
      - /Users/a2333/IDE/n8n/n8n-init:/docker-init-scripts:ro
    entrypoint: ["/docker-init-scripts/entrypoint.sh"]
