services:
  horizon:
    build: .
    container_name: horizon
    environment:
      - TZ=Asia/Shanghai
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env:ro
      - ./scripts/docker-run.sh:/scripts/docker-run.sh:ro
    entrypoint: ["/scripts/docker-run.sh"]
    restart: unless-stopped
